In [1]:
import numpy as np
a = np. array([10,20,30,40])
print("one dimensional array:",a)


one dimensional array: [10 20 30 40]


In [6]:
import numpy as np
b = np.array ([[10,20,30],[40,50,60]])
print("two dimensional array:",b)

two dimensional array: [[10 20 30]
 [40 50 60]]


In [8]:
import numpy as np
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("three dimensionl array:",c)

three dimensionl array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
import numpy as np
d = np.zeros((3,5))
print("\n array with all zeros\n:",d)


 array with all zeros
: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
import numpy as np
d = np.random.random((3,5))
print("\n random value:\n",d)


 random value:
 [[0.1841519  0.69522515 0.72426647 0.72587371 0.36477914]
 [0.17615833 0.66376304 0.85690191 0.95001803 0.59902142]
 [0.56961747 0.65678627 0.05306203 0.64089361 0.91266357]]


In [15]:
import numpy as np
e = np.arange(0,10,1)
print("\n sequence value:\n",e)


 sequence value:
 [0 1 2 3 4 5 6 7 8 9]


In [17]:
import numpy as np
orgarr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr = orgarr.reshape(4,3)
print("\n orginal array:\n",orgarr)
print("\n reshaped array:\n",newarr)


 orginal array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
import numpy as np
orgarr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flatarr = orgarr.flatten()
print("\n original array:\n",orgarr)
print("\n flatten array:\n",flatarr)



 original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [1]:
import numpy as np
h=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
size=len(h)
print("dimension array",h.ndim)
print("my array data types:",h.dtype)
print("length of array:",size)

dimension array 2
my array data types: int64
length of array: 4


In [2]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64
