In [1]:
import numpy as np
a=np.array([20,40,50,70,10])
b=np.array([6,2,9,7,11])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[20 40 50 70 10]
[ 6  2  9  7 11]
[26 42 59 77 21]
[14 38 41 63 -1]
[120  80 450 490 110]
[ 3.33333333 20.          5.55555556 10.          0.90909091]


In [2]:
#dot product
print(a.dot(b))
sclr=3
print("scalar value:",sclr)
print("Array:",a)
print("Result:",a*sclr)

1250
scalar value: 3
Array: [20 40 50 70 10]
Result: [ 60 120 150 210  30]


In [4]:
#vector operation
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [8]:
def my_fun(x,y):
    if x>y: 
        return x-y
    else:
        return x+y
arr1=[10,7,2]
arr2=[6,5,3]
vect_fun=np.vectorize(my_fun)
print("Array1:",arr1)
print("Array2:",arr2)
print("Result:",vect_fun(arr1,arr2))

Array1: [10, 7, 2]
Array2: [6, 5, 3]
Result: [4 2 5]
